<a href="https://colab.research.google.com/github/atshaya1208/Uber_project/blob/main/Uber_eats_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
import pandas as pd
import numpy as np
import ast

In [103]:
data = pd.read_csv("/content/Uber_Eats_data.csv")

In [104]:
data.shape

(23193, 13)

In [105]:
data.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [106]:
data.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [107]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23193 non-null  object
 1   online_order                 23193 non-null  object
 2   book_table                   23193 non-null  object
 3   rate                         23193 non-null  object
 4   votes                        23193 non-null  int64
 5   phone                        23193 non-null  object
 6   location                     23193 non-null  object
 7   rest_type                    23193 non-null  object
 8   dish_liked                   23193 non-null  object
 9   cuisines                     23193 non-null  object
 10  approx_cost(for two people)  23193 non-null  object
 11  listed_in(type)              23193 non-null  object
 12  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(12)
memory usage: 2.3+ MB

NAME

In [108]:
data['name']

0                                                    Jalsa
1                                           Spice Elephant
2                                          San Churro Cafe
3                                    Addhuri Udupi Bhojana
4                                            Grand Village
                               ...
23188                                   Izakaya Gastro Pub
23189          M Bar - Bengaluru Marriott Hotel Whitefield
23190                               Keys Cafe - Keys Hotel
23191                                              Bhagini
23192    Chime - Sheraton Grand Bengaluru Whitefield Ho...
Name: name, Length: 23193, dtype: object

In [109]:
data['name'].values[0]

'Jalsa'

In [110]:
data["name"].isnull().sum()

np.int64(0)

In [111]:
data.name = data.name.str.lower()
data.name = data.name.str.strip()
data.name

0                                                    jalsa
1                                           spice elephant
2                                          san churro cafe
3                                    addhuri udupi bhojana
4                                            grand village
                               ...
23188                                   izakaya gastro pub
23189          m bar - bengaluru marriott hotel whitefield
23190                               keys cafe - keys hotel
23191                                              bhagini
23192    chime - sheraton grand bengaluru whitefield ho...
Name: name, Length: 23193, dtype: object

In [112]:
data[data.duplicated()]

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
1532,the fisherman's wharf,Yes,Yes,4.4/5,4099,080 49653108,Sarjapur Road,"Casual Dining, Bar","Sea Food, Caesar Salad, Jumbo Prawns, Cocktail...","Seafood, Goan, North Indian, Continental, Asian","1,400",Buffet,Bellandur
1998,opus club,No,Yes,4.4/5,1496,+91 8046444777\r\n+91 7349734900,Sarjapur Road,Pub,"Biryani, Cocktails, Nachos, Mocktails, Long Is...","Continental, Italian, North Indian, Mexican","1,900",Drinks & nightlife,Bellandur
1999,float,Yes,Yes,4.4/5,3061,+91 9066887042\r\n+91 9066887086,Marathahalli,"Casual Dining, Bar","Butter Fish, Chicken Burritos, Cocktails, Mock...","North Indian, Japanese","1,500",Drinks & nightlife,Bellandur
2015,float,Yes,Yes,4.4/5,3061,+91 9066887042\r\n+91 9066887086,Marathahalli,"Casual Dining, Bar","Butter Fish, Chicken Burritos, Cocktails, Mock...","North Indian, Japanese","1,500",Pubs and bars,Bellandur
2887,fava,No,Yes,4.4/5,2039,080 49652925,Lavelle Road,"Casual Dining, Bar","Gnocchi, Cocktails, Pizza, Salads, Creme Brule...","Healthy Food, Mediterranean, Desserts, Italian...","1,200",Drinks & nightlife,Brigade Road
4243,vyanjan,Yes,No,3.9/5,201,+91 9916937446,BTM,Quick Bites,"Poha, Jalebi, Paratha, Bhindi Masala, Kachori,...","North Indian, Street Food",300,Delivery,BTM
4244,mid night hunting,Yes,No,3.7/5,127,+91 8892140430,Ejipura,"Takeaway, Delivery","Burgers, Chicken Burger, Pasta, Chicken Pizza","Fast Food, Italian",300,Delivery,BTM
4245,carrots,Yes,Yes,4.1/5,600,080 41172812,Koramangala 6th Block,Casual Dining,"Pizza, Pasta, Salads, Masala Chai, Soya Butter...","Italian, North Indian, Healthy Food, Desserts","1,100",Delivery,BTM
4246,rolls & co,Yes,No,3.9/5,213,+91 7353848635,Koramangala 6th Block,Quick Bites,"Rolls, Chicken Wings, Shawarma, Chicken Tikka ...","Burger, Beverages, Rolls",400,Delivery,BTM
4973,fenny's lounge and kitchen,No,Yes,4.5/5,6349,080 49653085,Koramangala 7th Block,"Bar, Casual Dining","Caramel Pudding, Cocktails, Pizza, Mocktails, ...","Mediterranean, Pizza, Continental, Seafood, Salad","1,600",Pubs and bars,BTM
5401,laughing llama gastropub,Yes,Yes,4.3/5,394,+91 9535029732,Brigade Road,"Bar, Casual Dining","Pancakes, Cocktails, Biryani, Draught Beer, Lo...","Finger Food, Continental, Pizza","1,600",Delivery,Church Street
5402,the bundle co.,Yes,No,4.4/5,223,+91 9148887222,MG Road,Quick Bites,"Burgers, Salad, Mocktails, Pasta Arrabiata, Fr...","Burger, Continental, Italian, Beverages",700,Delivery,Church Street
5410,moto store & cafãâãâãâãâãâãâãâãâ©,Yes,No,4.2/5,382,080 49653126,Ulsoor,Cafe,"Wedges, Maggi, Burgers, Waffles, Margherita Pi...","Pizza, Italian, Cafe, Burger, Finger Food, Fas...",500,Delivery,Church Street
5411,hoppipola,Yes,No,4.3/5,1708,+91 9620216162,Church Street,Lounge,"Masala Peanuts, Cocktails, Paratha, Pizza, Pas...","Continental, Mediterranean, European","1,300",Delivery,Church Street
5417,99 pancakes,Yes,No,4.1/5,41,+91 7483655827,Church Street,Dessert Parlor,Nutella Pancakes,"Desserts, Ice Cream",150,Delivery,Church Street
5418,nolimmits lounge and club,Yes,Yes,4.0/5,2112,080 49653274,Brigade Road,Club,"Salads, Chicken Bbq Wings, Sandwiches, Pasta, ...","Chinese, Continental, North Indian, Burger, Pizza","2,000",Delivery,Church Street
6021,lassi adda,Yes,No,4.0/5,65,+91 9164247999\r\n+91 9986382545,Electronic City,Beverage Shop,"Sweet Lassi, Corn Sandwich","Beverages, Sandwich, Fast Food",200,Delivery,Electronic City
7282,cinnamon,Yes,No,3.9/5,450,+91 9900890054\r\n080 41201897,HSR,Casual Dining,"Raita, Tandoori Chicken, Egg Chilli, Hakka Noo...","North Indian, Chinese, Biryani",550,Delivery,HSR
8168,nevermind - bar & social,No,Yes,NEW,0,080 49652505,Indiranagar,"Casual Dining, Bar","Pasta, Nachos, Beef Teriyaki, Pizza","Continental, Asian, Modern Indian","1,700",Dine-out,Indiranagar
8174,sly granny - the community house,No,Yes,4.4/5,953,080 48536712\r\n080 48536715,Indiranagar,"Fine Dining, Bar","Cocktails, Pie, Rolls, Mezze Platter, Schnitze...","Modern Indian, European, American","2,500",Dine-out,Indiranagar
8900,toscano,Yes,Yes,4.5/5,715,080 22067757\r\n+91 7619320075,Koramangala 7th Block,Casual Dining,"Pizza, Pasta, Cocktails, Spinach Ravioli, Tira...","Italian, Salad","1,500",Delivery,Jayanagar
9085,funky punjab,Yes,No,3.8/5,125,+91 8884449474,BTM,Quick Bites,"Roti, Dal Makhani, Lassi, Panneer Butter Masal...","North Indian, Chinese",400,Delivery,Jayanagar
10763,victoria terminus,Yes,No,2.9/5,54,+91 9686933734\r\n+91 9066157771,Banaswadi,Quick Bites,"Vada Pav, Kulfi, Mumbai Sandwich, Rolls, Keema...","Fast Food, Maharashtrian, Rolls",250,Delivery,Kalyan Nagar
13688,chinita real mexican food,No,No,4.5 /5,733,+91 9591038009\r\n080 43711400,Koramangala 5th Block,Casual Dining,"Tacos, Churros, Nachos, Salad, Enchiladas, Bur...",Mexican,"1,200",Dine-out,Koramangala 5th Block
13846,154 breakfast club,Yes,Yes,4.0 /5,1515,080 25533133,Koramangala 3rd Block,Cafe,"Pancakes, Waffles, Bbq Sandwich, Mushroom Rago...","Cafe, Continental",900,Dine-out,Koramangala 5th Block
16820,the oriental spice - ashraya hotel,Yes,No,3.9 /5,158,080 41148989\n+91 7795612130,Infantry Road,Casual Dining,"Noodles, Lunch Buffet, Fish, Manchurian, Salad...","Chinese, Thai, Indonesian","1,300",Buffet,Lavelle Road
17253,rasovara,Yes,Yes,4.3 /5,772,080 41738968\n+91 9886060965,Lavelle Road,Casual Dining,"Thali, Aamras, Malpua, Dal Bati, Lassi, Plain ...","Rajasthani, North Indian","1,400",Dine-out,Lavelle Road
18575,sizzling pasto,Yes,Yes,4.1 /5,99,080 49652891,Marathahalli,"Casual Dining, Bar","Mocktails, Brownie, Sangria, Cocktail Prawn, S...","Continental, Chinese, North Indian","1,100",Dine-out,Marathahalli
18931,red onion,Yes,Yes,4.2 /5,570,080 40918141\n+91 8867785004,Shanti Nagar,Casual Dining,"Fish, Dumplings, Biryani, Paneer Tikka Masala,...","Chinese, North Indian, Biryani, Kebab","1,200",Delivery,MG Road
19487,bootlegger,No,No,4.1 /5,1545,+91 8022290099\n+91 8041462747,Lavelle Road,Pub,"Beer, Cocktails, Beef Steak, Beef Chilli, Nach...","Continental, Steak","1,200",Dine-out,MG Road
19501,ithaca - the chancery pavilion,No,Yes,3.9 /5,312,+91 9902785566,Residency Road,Fine Dining,"Salads, Sunday Brunch, Cocktails, Watermelon J...","North Indian, Italian, European, Continental","2,000",Dine-out,MG Road
19718,alchemy - the chancery pavilion,No,Yes,4.3 /5,485,080 49653555,Residency Road,"Microbrewery, Casual Dining","Craft Beer, Cocktails, Stout, Chicken Wings, F...",Modern Indian,"2,000",Drinks & nightlife,MG Road
20785,tipsy bull - the bar exchange,No,Yes,4.6 /5,3173,080 49652910,Indiranagar,"Bar, Casual Dining","Cocktails, Peri Peri Chicken, Biryani, Mocktai...","Chinese, Continental, North Indian, Mexican","1,400",Drinks & nightlife,Old Airport Road
20786,btdt? been there done that,No,Yes,4.3 /5,962,080 49652655,Indiranagar,"Bar, Casual Dining","Cocktails, Momos, Pizza, Mushroom Ragout, Roti...","European, Continental, Asian, Finger Food","1,300",Drinks & nightlife,Old Airport Road
22014,shakesbierre,No,Yes,4.4 /5,409,080 49653253,Brigade Road,"Microbrewery, Casual Dining","Cocktails, Mocktails, Pizza, Sweet Yogurt, Juj...","Asian, Continental, European, North Indian","1,500",Drinks & nightlife,Residency Road

In [113]:
data.duplicated().sum()

np.int64(35)

In [114]:
data = data.drop_duplicates(keep = 'last')

In [115]:
data.duplicated().sum()

np.int64(0)

ONLINE ORDER

In [116]:
data['online_order']

0        Yes
1        Yes
2        Yes
3         No
4         No
        ...
23188    Yes
23189     No
23190     No
23191     No
23192     No
Name: online_order, Length: 23158, dtype: object

In [117]:
data['online_order'].values[0]

'Yes'

In [118]:
data.online_order.values

array(['Yes', 'Yes', 'Yes', ..., 'No', 'No', 'No'], dtype=object)

In [119]:
data['online_order'].value_counts()

online_order
Yes    16335
No      6823
Name: count, dtype: int64

In [120]:
data['online_order'] = data['online_order'].str.lower()
data['online_order'] = data['online_order'].str.strip()
data['online_order']

0        yes
1        yes
2        yes
3         no
4         no
        ...
23188    yes
23189     no
23190     no
23191     no
23192     no
Name: online_order, Length: 23158, dtype: object

In [121]:
data['online_order'].isnull().sum()

np.int64(0)

In [122]:
data

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,jalsa,yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,spice elephant,yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,san churro cafe,yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,addhuri udupi bhojana,no,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,grand village,no,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,izakaya gastro pub,yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,m bar - bengaluru marriott hotel whitefield,no,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,keys cafe - keys hotel,no,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,bhagini,no,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,chime - sheraton grand bengaluru whitefield ho...,no,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

BOOK TABLE

In [123]:
data['book_table']

0        Yes
1         No
2         No
3         No
4         No
        ...
23188    Yes
23189     No
23190     No
23191     No
23192    Yes
Name: book_table, Length: 23158, dtype: object

In [124]:
data['book_table'].values

array(['Yes', 'No', 'No', ..., 'No', 'No', 'Yes'], dtype=object)

In [125]:
data['book_table'].value_counts()

book_table
No     17057
Yes     6101
Name: count, dtype: int64

In [126]:
data['book_table'] = data['book_table'].str.lower()
data['book_table'] = data['book_table'].str.strip()
data['book_table']

0        yes
1         no
2         no
3         no
4         no
        ...
23188    yes
23189     no
23190     no
23191     no
23192    yes
Name: book_table, Length: 23158, dtype: object

In [127]:
data['book_table'].isnull().sum()

np.int64(0)

RATINGS

In [128]:
data['rate'].values[0]

'4.1/5'

In [129]:
data.rate.dtype

dtype('O')

In [130]:
data.rate.value_counts()

rate
3.9/5     1686
3.9 /5    1547
4.0/5     1467
4.1/5     1396
4.0 /5    1390
          ...
2.2 /5       7
2.0 /5       7
2.0/5        4
1.8 /5       3
1.8/5        2
Name: count, Length: 63, dtype: int64

In [131]:
data.rate.isnull().sum()

np.int64(0)

In [132]:
ratings = []
for i in data['rate']:
  if i == 'NEW' or i == '-':
    ratings.append(np.nan)
  else:
    i = str(i).split('/')[0]
    ratings.append(i)
data['rate'] = ratings

In [133]:
data['rate'].value_counts()

rate
3.9     1686
3.9     1547
4.0     1467
4.1     1396
4.0     1390
        ...
2.2        7
2.0        7
2.0        4
1.8        3
1.8        2
Name: count, Length: 62, dtype: int64

In [134]:
data.rate.isnull().sum()

np.int64(146)

In [135]:
data = data.dropna(subset=['rate'])

In [136]:
data.rate.isnull().sum()

np.int64(0)

In [137]:
data['rate'] = data['rate'].astype(float)

/tmp/ipykernel_6159/1957175498.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['rate'] = data['rate'].astype(float)

In [138]:
data['rate'].dtype

dtype('float64')

In [139]:
data.rate.describe()

count    23012.000000
mean         3.904002
std          0.426388
min          1.800000
25%          3.800000
50%          4.000000
75%          4.200000
max          4.900000
Name: rate, dtype: float64

VOTE

In [140]:
data.votes

0        775
1        787
2        918
3         88
4        166
        ...
23188    128
23189     77
23190    161
23191     81
23192    236
Name: votes, Length: 23012, dtype: int64

In [141]:
data['votes'].values[0]

np.int64(775)

In [142]:
data.votes.isnull().sum()

np.int64(0)

In [143]:
data['votes'].value_counts()

votes
61      140
53      136
46      126
48      115
74      112
       ...
3730      1
2749      1
2292      1
1359      1
2034      1
Name: count, Length: 2283, dtype: int64

In [144]:
data.votes.dtype

dtype('int64')

In [145]:
data.votes.describe()

count    23012.000000
mean       604.098688
std       1116.738081
min          0.000000
25%        103.000000
50%        224.000000
75%        590.000000
max      16832.000000
Name: votes, dtype: float64

PHONE NUMBER

In [146]:
data.phone

0          080 42297555\r\n+91 9743772233
1                            080 41714161
2                          +91 9663487993
3                          +91 9620009302
4        +91 8026612447\r\n+91 9901210005
                       ...
23188      +91 7625087121\n+91 8050587483
23189                        080 49435000
23190        080 39451000\n+91 8884038484
23191                        080 65951222
23192                        080 49652769
Name: phone, Length: 23012, dtype: object

In [147]:
data.phone.values[0]

'080 42297555\r\n+91 9743772233'

In [148]:
data.phone.isnull().sum()

np.int64(0)

In [149]:
data['phone'] = data['phone'].str.replace('\r\n',',')
data['phone'] = data['phone'].str.strip()
data['phone']

/tmp/ipykernel_6159/1947024104.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['phone'] = data['phone'].str.replace('\r\n',',')
/tmp/ipykernel_6159/1947024104.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['phone'] = data['phone'].str.strip()

0           080 42297555,+91 9743772233
1                          080 41714161
2                        +91 9663487993
3                        +91 9620009302
4         +91 8026612447,+91 9901210005
                      ...
23188    +91 7625087121\n+91 8050587483
23189                      080 49435000
23190      080 39451000\n+91 8884038484
23191                      080 65951222
23192                      080 49652769
Name: phone, Length: 23012, dtype: object

LOCATION

In [150]:
data.location

0                      Banashankari
1                      Banashankari
2                      Banashankari
3                      Banashankari
4                      Basavanagudi
                    ...
23188                    Whitefield
23189                    Whitefield
23190                    Whitefield
23191                    Whitefield
23192    ITPL Main Road, Whitefield
Name: location, Length: 23012, dtype: object

In [151]:
data.location.values[0]

'Banashankari'

In [152]:
data.location.value_counts()

location
Koramangala 5th Block    1759
BTM                      1444
Indiranagar              1331
HSR                      1154
Jayanagar                1030
                         ...
Kanakapura Road             2
West Bangalore              2
Yelahanka                   2
Magadi Road                 2
KR Puram                    1
Name: count, Length: 88, dtype: int64

In [153]:
data.location.isnull().sum()

np.int64(0)

In [154]:
data.location = data.location.str.lower()
data.location = data.location.str.strip()
data.location

/tmp/ipykernel_6159/1752838122.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.location = data.location.str.lower()
/tmp/ipykernel_6159/1752838122.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.location = data.location.str.strip()

0                      banashankari
1                      banashankari
2                      banashankari
3                      banashankari
4                      basavanagudi
                    ...
23188                    whitefield
23189                    whitefield
23190                    whitefield
23191                    whitefield
23192    itpl main road, whitefield
Name: location, Length: 23012, dtype: object

REST TYPE

In [155]:
data.rest_type

0              Casual Dining
1              Casual Dining
2        Cafe, Casual Dining
3                Quick Bites
4              Casual Dining
                ...
23188     Bar, Casual Dining
23189       Fine Dining, Bar
23190     Casual Dining, Bar
23191     Casual Dining, Bar
23192                    Bar
Name: rest_type, Length: 23012, dtype: object

In [156]:
data.rest_type.values[0]

'Casual Dining'

In [157]:
data.rest_type.value_counts()

rest_type
Casual Dining                7291
Quick Bites                  5219
Cafe                         2319
Dessert Parlor               1073
Casual Dining, Bar            975
                             ...
Fine Dining, Microbrewery       5
Club, Casual Dining             4
Dessert Parlor, Kiosk           2
Dhaba                           1
Food Court, Casual Dining       1
Name: count, Length: 73, dtype: int64

In [158]:
data.rest_type.isnull().sum()

np.int64(0)

In [159]:
data.rest_type = data.rest_type.str.lower()
data.rest_type = data.rest_type.str.strip()
data.rest_type

/tmp/ipykernel_6159/562940965.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.rest_type = data.rest_type.str.lower()
/tmp/ipykernel_6159/562940965.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.rest_type = data.rest_type.str.strip()

0              casual dining
1              casual dining
2        cafe, casual dining
3                quick bites
4              casual dining
                ...
23188     bar, casual dining
23189       fine dining, bar
23190     casual dining, bar
23191     casual dining, bar
23192                    bar
Name: rest_type, Length: 23012, dtype: object

DISH LIKED

In [160]:
data.dish_liked

0        Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
1        Momos, Lunch Buffet, Chocolate Nirvana, Thai G...
2        Churros, Cannelloni, Minestrone Soup, Hot Choc...
3                                              Masala Dosa
4                                      Panipuri, Gol Gappe
                               ...
23188    Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...
23189                                     Rooftop Ambience
23190    Salads, Coffee, Breakfast Buffet, Halwa, Chick...
23191                                 Biryani, Andhra Meal
23192                         Cocktails, Pizza, Buttermilk
Name: dish_liked, Length: 23012, dtype: object

In [161]:
data.dish_liked.values[0]

'Pasta, Lunch Buffet, Masala Papad, Paneer Lajawab, Tomato Shorba, Dum Biryani, Sweet Corn Soup'

In [162]:
data['dish_liked'].value_counts()

dish_liked
Biryani                                                                                             179
Friendly Staff                                                                                       68
Waffles                                                                                              67
Chicken Biryani                                                                                      66
Masala Dosa                                                                                          56
                                                                                                   ...
Pasta, Creme Brulee, Tiramisu, Bbq Chicken Pizza, Steak, Salads, Wine                                 1
Cocktails, Panna Cotta, Lamb Pizza, Pita Bread                                                        1
Murgh Platter, Dessert Platter, Chicken Sizzler, Tiramisu, Lobster, Mocktails, Vegetable Biryani      1
Coffee, Raj Kachori, Idli, Vada, Tea, Masala Dosa, Chaat                                              1
Masala Dosa, Filter Coffee, Curd Rice                                                                 1
Name: count, Length: 5145, dtype: int64

In [163]:
data.dish_liked.isnull().sum()

np.int64(0)

In [164]:
data.dish_liked = data.dish_liked.str.lower()
data.dish_liked = data.dish_liked.str.strip()
data.dish_liked

/tmp/ipykernel_6159/577090098.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dish_liked = data.dish_liked.str.lower()
/tmp/ipykernel_6159/577090098.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dish_liked = data.dish_liked.str.strip()

0        pasta, lunch buffet, masala papad, paneer laja...
1        momos, lunch buffet, chocolate nirvana, thai g...
2        churros, cannelloni, minestrone soup, hot choc...
3                                              masala dosa
4                                      panipuri, gol gappe
                               ...
23188    beer, chicken guntur, paneer tikka, fish, nood...
23189                                     rooftop ambience
23190    salads, coffee, breakfast buffet, halwa, chick...
23191                                 biryani, andhra meal
23192                         cocktails, pizza, buttermilk
Name: dish_liked, Length: 23012, dtype: object

CUISINES

In [165]:
data.cuisines

0                     North Indian, Mughlai, Chinese
1                        Chinese, North Indian, Thai
2                             Cafe, Mexican, Italian
3                         South Indian, North Indian
4                           North Indian, Rajasthani
                            ...
23188       North Indian, Continental, Mediterranean
23189                                    Finger Food
23190             Chinese, Continental, North Indian
23191    Andhra, South Indian, Chinese, North Indian
23192                                    Finger Food
Name: cuisines, Length: 23012, dtype: object

In [166]:
data.cuisines.values[0]

'North Indian, Mughlai, Chinese'

In [167]:
data.cuisines.value_counts()

cuisines
North Indian                           1136
North Indian, Chinese                   776
South Indian                            359
Cafe                                    273
South Indian, North Indian, Chinese     233
                                       ...
Tibetan, Nepalese                         1
South Indian, Chettinad                   1
Andhra, Hyderabadi, Biryani               1
Andhra, North Indian, South Indian        1
Thai, Chinese, Momos                      1
Name: count, Length: 1677, dtype: int64

In [168]:
data.cuisines.isnull().sum()

np.int64(0)

In [169]:
data.cuisines = data.cuisines.str.lower()
data.cuisines = data.cuisines.str.strip()
data.cuisines

/tmp/ipykernel_6159/3695237108.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.cuisines = data.cuisines.str.lower()
/tmp/ipykernel_6159/3695237108.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.cuisines = data.cuisines.str.strip()

0                     north indian, mughlai, chinese
1                        chinese, north indian, thai
2                             cafe, mexican, italian
3                         south indian, north indian
4                           north indian, rajasthani
                            ...
23188       north indian, continental, mediterranean
23189                                    finger food
23190             chinese, continental, north indian
23191    andhra, south indian, chinese, north indian
23192                                    finger food
Name: cuisines, Length: 23012, dtype: object

AMOUNT FOR TWO PEOPLE

In [170]:
data['approx_cost(for two people)']

0          800
1          800
2          800
3          300
4          600
         ...
23188    1,200
23189    2,000
23190    1,200
23191      800
23192    2,500
Name: approx_cost(for two people), Length: 23012, dtype: object

In [171]:
data['approx_cost(for two people)'].values[0]

'800'

In [172]:
data['approx_cost(for two people)'].value_counts()

approx_cost(for two people)
400      2458
500      2268
600      2163
300      1680
800      1641
1,000    1218
700      1154
1,200     894
200       857
1,500     829
450       718
250       692
750       652
650       636
350       553
900       513
1,300     494
1,100     444
550       439
1,400     437
150       366
2,000     294
1,600     235
1,700     229
1,800     189
3,000     159
2,500     142
850       122
100       117
2,100      60
1,900      57
950        47
2,200      39
2,800      31
3,500      25
4,000      24
2,400      22
1,350      18
180        17
3,400      13
230        10
40          8
1,250       8
1,650       6
1,450       5
330         4
4,100       4
2,600       4
1,050       4
3,200       2
6,000       2
2,700       2
120         2
4,500       2
2,300       1
5,000       1
3,700       1
Name: count, dtype: int64

In [173]:
data['approx_cost(for two people)'].isnull().sum()

np.int64(0)

In [174]:
import ast
data['approx_cost(for two people)'] = data['approx_cost(for two people)'].str.replace(',','')
data['approx_cost(for two people)'] = data['approx_cost(for two people)'].astype('int')
data['approx_cost(for two people)']

/tmp/ipykernel_6159/2218977212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['approx_cost(for two people)'] = data['approx_cost(for two people)'].str.replace(',','')
/tmp/ipykernel_6159/2218977212.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['approx_cost(for two people)'] = data['approx_cost(for two people)'].astype('int')

0         800
1         800
2         800
3         300
4         600
         ...
23188    1200
23189    2000
23190    1200
23191     800
23192    2500
Name: approx_cost(for two people), Length: 23012, dtype: int64

In [175]:
data['approx_cost(for two people)'].dtype

dtype('int64')

In [176]:
data['approx_cost(for two people)'].describe()

count    23012.000000
mean       753.704154
std        521.191287
min         40.000000
25%        400.000000
50%        600.000000
75%       1000.000000
max       6000.000000
Name: approx_cost(for two people), dtype: float64

In [177]:
data.rename(columns={'approx_cost(for two people)':'cost_for_two_people'},inplace=True)

/tmp/ipykernel_6159/4117708203.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.rename(columns={'approx_cost(for two people)':'cost_for_two_people'},inplace=True)

In [178]:
data.shape

(23012, 13)

TYPES OF RESTAURANT

In [179]:
data['listed_in(type)']

0               Buffet
1               Buffet
2               Buffet
3               Buffet
4               Buffet
             ...
23188    Pubs and bars
23189    Pubs and bars
23190    Pubs and bars
23191    Pubs and bars
23192    Pubs and bars
Name: listed_in(type), Length: 23012, dtype: object

In [180]:
data['listed_in(type)'].values[0]

'Buffet'

In [181]:
data['listed_in(type)'].value_counts()

listed_in(type)
Delivery              10559
Dine-out               7947
Desserts               1330
Cafes                  1046
Drinks & nightlife      864
Buffet                  751
Pubs and bars           515
Name: count, dtype: int64

In [182]:
data['listed_in(type)'].isnull().sum()

np.int64(0)

In [183]:
data['listed_in(type)'] = data['listed_in(type)'].str.lower()
data['listed_in(type)'] = data['listed_in(type)'].str.strip()
data['listed_in(type)']

/tmp/ipykernel_6159/2327586653.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['listed_in(type)'] = data['listed_in(type)'].str.lower()
/tmp/ipykernel_6159/2327586653.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['listed_in(type)'] = data['listed_in(type)'].str.strip()

0               buffet
1               buffet
2               buffet
3               buffet
4               buffet
             ...
23188    pubs and bars
23189    pubs and bars
23190    pubs and bars
23191    pubs and bars
23192    pubs and bars
Name: listed_in(type), Length: 23012, dtype: object

In [184]:
data.rename(columns={'listed_in(type)':'type_of_restaurant'},inplace=True)

/tmp/ipykernel_6159/691982855.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.rename(columns={'listed_in(type)':'type_of_restaurant'},inplace=True)

CITY

In [185]:
data['listed_in(city)']

0        Banashankari
1        Banashankari
2        Banashankari
3        Banashankari
4        Banashankari
             ...
23188      Whitefield
23189      Whitefield
23190      Whitefield
23191      Whitefield
23192      Whitefield
Name: listed_in(city), Length: 23012, dtype: object

In [186]:
data['listed_in(city)'].values[0]

'Banashankari'

In [187]:
data['listed_in(city)'].value_counts()

listed_in(city)
BTM                      1399
Koramangala 7th Block    1357
Koramangala 4th Block    1331
Koramangala 5th Block    1291
Koramangala 6th Block    1237
Jayanagar                1040
Indiranagar              1010
MG Road                  1003
Church Street             973
Brigade Road              963
Lavelle Road              893
Residency Road            839
JP Nagar                  809
Old Airport Road          743
HSR                       729
Whitefield                627
Marathahalli              618
Brookefield               595
Basavanagudi              594
Frazer Town               544
Bannerghatta Road         540
Kammanahalli              530
Kalyan Nagar              515
Bellandur                 497
Sarjapur Road             496
Malleshwaram              492
Rajajinagar               374
Banashankari              372
Electronic City           319
New BEL Road              282
Name: count, dtype: int64

In [188]:
data = data.drop(columns = ['listed_in(city)'])

In [189]:
data.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two_people,type_of_restaurant
0,jalsa,yes,yes,4.1,775,"080 42297555,+91 9743772233",banashankari,casual dining,"pasta, lunch buffet, masala papad, paneer laja...","north indian, mughlai, chinese",800,buffet
1,spice elephant,yes,no,4.1,787,080 41714161,banashankari,casual dining,"momos, lunch buffet, chocolate nirvana, thai g...","chinese, north indian, thai",800,buffet
2,san churro cafe,yes,no,3.8,918,+91 9663487993,banashankari,"cafe, casual dining","churros, cannelloni, minestrone soup, hot choc...","cafe, mexican, italian",800,buffet
3,addhuri udupi bhojana,no,no,3.7,88,+91 9620009302,banashankari,quick bites,masala dosa,"south indian, north indian",300,buffet
4,grand village,no,no,3.8,166,"+91 8026612447,+91 9901210005",basavanagudi,casual dining,"panipuri, gol gappe","north indian, rajasthani",600,buffet

In [190]:
data['name'] = data['name'].str.replace(r'[^a-zA-Z0-9 ]', '', regex=True)

In [191]:
data.duplicated().sum()

np.int64(5025)

In [192]:
data = data.drop_duplicates(keep = 'last')

In [193]:
data.duplicated().sum()

np.int64(0)

In [194]:
data.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two_people,type_of_restaurant
1,spice elephant,yes,no,4.1,787,080 41714161,banashankari,casual dining,"momos, lunch buffet, chocolate nirvana, thai g...","chinese, north indian, thai",800,buffet
3,addhuri udupi bhojana,no,no,3.7,88,+91 9620009302,banashankari,quick bites,masala dosa,"south indian, north indian",300,buffet
6,onesta,yes,yes,4.6,2556,"080 48653961,080 48655715",banashankari,"casual dining, cafe","farmhouse pizza, chocolate banana, virgin moji...","pizza, cafe, italian",600,cafes
9,caf down the alley,yes,no,4.1,402,"080 26724489,+91 7406048982",banashankari,cafe,"waffles, pasta, crispy chicken, honey chilli c...",cafe,500,cafes
11,the coffee shack,yes,yes,4.2,164,+91 9731644212,banashankari,cafe,"coffee, spaghetti, pancakes, nachos, pasta, sa...","cafe, chinese, continental, italian",500,cafes

In [195]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17987 entries, 1 to 23192
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 17987 non-null  object
 1   online_order         17987 non-null  object
 2   book_table           17987 non-null  object
 3   rate                 17987 non-null  float64
 4   votes                17987 non-null  int64
 5   phone                17987 non-null  object
 6   location             17987 non-null  object
 7   rest_type            17987 non-null  object
 8   dish_liked           17987 non-null  object
 9   cuisines             17987 non-null  object
 10  cost_for_two_people  17987 non-null  int64
 11  type_of_restaurant   17987 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 1.8+ MB

In [196]:
data.shape

(17987, 12)

In [197]:
data.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'cost_for_two_people', 'type_of_restaurant'],
      dtype='object')

In [198]:
Uber_Eats_data = data.to_csv('uber_cleaned_data.csv', index=False)

ORDERS DATA

In [199]:
df = pd.read_json('/content/orders.json')

In [200]:
df.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI

In [201]:
df.shape

(25000, 6)

In [202]:
df.columns

Index(['order_id', 'restaurant_name', 'order_date', 'order_value',
       'discount_used', 'payment_method'],
      dtype='object')

In [203]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         25000 non-null  object
 1   restaurant_name  25000 non-null  object
 2   order_date       25000 non-null  object
 3   order_value      25000 non-null  float64
 4   discount_used    25000 non-null  object
 5   payment_method   25000 non-null  object
dtypes: float64(1), object(5)
memory usage: 1.1+ MB

In [204]:
df['order_id']

0        8174c2af-07a4-4837-9068-1169d963e36e
1        0f9ddb57-4632-4a9f-9afe-1d2e41b94e32
2        099deda6-8c53-41cb-abf8-00126e6b2643
3        94a6ba27-d6ef-4d10-a026-ac0c0afa8505
4        216f3ec7-80a9-4d95-872f-715c37163b6d
                         ...
24995    74d3cd31-c1e0-4331-aad7-e1f48b4698ae
24996    14db2f6b-f722-44a2-ae55-fe42511e4bb2
24997    0fd85321-c1ce-4163-beca-c8ed2b472b8d
24998    6b96c699-2d63-4a3c-84f1-5d52ca4bf357
24999    af55e28b-27fc-49fc-bdb0-b297999dd152
Name: order_id, Length: 25000, dtype: object

In [205]:
df['order_id'].values[0]

'8174c2af-07a4-4837-9068-1169d963e36e'

In [206]:
df['order_id'].value_counts()

order_id
af55e28b-27fc-49fc-bdb0-b297999dd152    1
8174c2af-07a4-4837-9068-1169d963e36e    1
0f9ddb57-4632-4a9f-9afe-1d2e41b94e32    1
099deda6-8c53-41cb-abf8-00126e6b2643    1
94a6ba27-d6ef-4d10-a026-ac0c0afa8505    1
                                       ..
00a0c73e-b797-4322-afc4-6199d5f68ce9    1
11c7ea0f-cafa-4b63-a14e-7129fa934e95    1
28bcfd85-fd84-458c-851b-60311c625d01    1
25b2d40b-35b3-40f7-9cbe-37bf690db837    1
e44b23ce-6d29-4c09-9eac-9d4f24f56fd9    1
Name: count, Length: 25000, dtype: int64

In [207]:
df['order_id'].isnull().sum()

np.int64(0)

In [208]:
df.order_id = df.order_id.str.lower()
df.order_id = df.order_id.str.strip()
df.order_id

0        8174c2af-07a4-4837-9068-1169d963e36e
1        0f9ddb57-4632-4a9f-9afe-1d2e41b94e32
2        099deda6-8c53-41cb-abf8-00126e6b2643
3        94a6ba27-d6ef-4d10-a026-ac0c0afa8505
4        216f3ec7-80a9-4d95-872f-715c37163b6d
                         ...
24995    74d3cd31-c1e0-4331-aad7-e1f48b4698ae
24996    14db2f6b-f722-44a2-ae55-fe42511e4bb2
24997    0fd85321-c1ce-4163-beca-c8ed2b472b8d
24998    6b96c699-2d63-4a3c-84f1-5d52ca4bf357
24999    af55e28b-27fc-49fc-bdb0-b297999dd152
Name: order_id, Length: 25000, dtype: object

In [209]:
df.duplicated().sum()

np.int64(0)

In [210]:
df.restaurant_name

0                 TBC Sky Lounge
1        KC Das - Sweet Paradise
2              Hotel Kadamba Veg
3                  Cafe Srinidhi
4                         Pebble
                  ...
24995                   Carnatic
24996         Reddy's Restaurant
24997       BTM Bawarchi Biryani
24998                   Nite Out
24999                  Zee5 Loft
Name: restaurant_name, Length: 25000, dtype: object

In [211]:
df.restaurant_name.values[0]

'TBC Sky Lounge'

In [212]:
df.restaurant_name.value_counts()

restaurant_name
Andhra Grills                              19
Cake Cafe                                  19
Hungry Lee                                 18
Shree Muthahalli Veg                       18
Orbis Restaurant                           18
                                           ..
24@43 - The Oterra                          1
Swathi Maharaja                             1
The Barn - Bar & Kitchen                    1
The Hub & The Bar - Hotel Ramada Encore     1
Kamat Bugle Rock                            1
Name: count, Length: 3159, dtype: int64

In [213]:
df['restaurant_name'] = df['restaurant_name'].str.replace(r'[^a-zA-Z0-9 ]', '', regex=True)

In [214]:
df.restaurant_name.isnull().sum()

np.int64(0)

In [215]:
df.restaurant_name = df.restaurant_name.str.lower()
df.restaurant_name = df.restaurant_name.str.strip()
df.restaurant_name

0                tbc sky lounge
1        kc das  sweet paradise
2             hotel kadamba veg
3                 cafe srinidhi
4                        pebble
                  ...
24995                  carnatic
24996         reddys restaurant
24997      btm bawarchi biryani
24998                  nite out
24999                 zee5 loft
Name: restaurant_name, Length: 25000, dtype: object

In [216]:
df.order_date

0        2025-05-06
1        2026-01-08
2        2026-01-22
3        2025-11-10
4        2025-12-22
            ...
24995    2025-11-24
24996    2025-06-24
24997    2025-12-04
24998    2025-09-21
24999    2025-08-07
Name: order_date, Length: 25000, dtype: object

In [217]:
df.order_date.values[0]

'2025-05-06'

In [218]:
import datetime

In [219]:
df.order_date = pd.to_datetime(df.order_date, format="%Y-%m-%d")

In [220]:
df.order_date.isnull().sum()

np.int64(0)

In [221]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         25000 non-null  object
 1   restaurant_name  25000 non-null  object
 2   order_date       25000 non-null  datetime64[ns]
 3   order_value      25000 non-null  float64
 4   discount_used    25000 non-null  object
 5   payment_method   25000 non-null  object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 1.1+ MB
None

In [222]:
df.order_value

0         201.87
1        1392.27
2        1358.35
3         782.37
4        1551.09
          ...
24995    1254.91
24996     760.39
24997     707.99
24998     724.29
24999     905.00
Name: order_value, Length: 25000, dtype: float64

In [223]:
df.order_value = df.order_value.astype(int)

In [224]:
df.order_value.value_counts()

order_value
1229    32
585     30
381     30
1377    29
784     29
        ..
1942     2
1552     2
177      2
1605     2
1570     1
Name: count, Length: 1850, dtype: int64

In [225]:
df.order_value.isnull().sum()

np.int64(0)

In [226]:
df.order_value.describe()

count    25000.000000
mean       985.585320
std        472.950179
min        150.000000
25%        589.000000
50%        966.000000
75%       1344.000000
max       1999.000000
Name: order_value, dtype: float64

In [227]:
df.discount_used

0         No
1         No
2        Yes
3         No
4        Yes
        ...
24995     No
24996     No
24997    Yes
24998    Yes
24999     No
Name: discount_used, Length: 25000, dtype: object

In [228]:
df.discount_used.value_counts()

discount_used
No     12509
Yes    12491
Name: count, dtype: int64

In [229]:
df.discount_used = df.discount_used.str.lower()
df.discount_used = df.discount_used.str.strip()
df.discount_used

0         no
1         no
2        yes
3         no
4        yes
        ...
24995     no
24996     no
24997    yes
24998    yes
24999     no
Name: discount_used, Length: 25000, dtype: object

In [230]:
df.discount_used.isnull().sum()

np.int64(0)

In [231]:
df.payment_method

0        Card
1        Cash
2         UPI
3         UPI
4         UPI
         ...
24995     UPI
24996    Card
24997    Card
24998    Card
24999     UPI
Name: payment_method, Length: 25000, dtype: object

In [232]:
df.payment_method.value_counts()

payment_method
Cash    8384
Card    8364
UPI     8252
Name: count, dtype: int64

In [233]:
df['payment_method'] = df['payment_method'].str.lower()
df['payment_method'] = df['payment_method'].str.strip()
df['payment_method']

0        card
1        cash
2         upi
3         upi
4         upi
         ...
24995     upi
24996    card
24997    card
24998    card
24999     upi
Name: payment_method, Length: 25000, dtype: object

In [234]:
df.payment_method.isnull().sum()

np.int64(0)

In [235]:
df = df.drop_duplicates(subset=['order_id'])

In [236]:
df.duplicated().sum()

np.int64(0)

In [237]:
df.shape

(25000, 6)

In [238]:
df.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,tbc sky lounge,2025-05-06,201,no,card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,kc das sweet paradise,2026-01-08,1392,no,cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,hotel kadamba veg,2026-01-22,1358,yes,upi
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,cafe srinidhi,2025-11-10,782,no,upi
4,216f3ec7-80a9-4d95-872f-715c37163b6d,pebble,2025-12-22,1551,yes,upi

In [239]:
Order_data = df.to_csv('Order_data.csv', index= False)